# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/custom_ip/managed_ip_project/managed_ip_project.tmp/our_dac_v1_0_project/our_dac_v1_0_project.cache/wt [current_project]
set_property parent.project_path D:/custom_ip/managed_ip_project/managed_ip_project.tmp/our_dac_v1_0_project/our_dac_v1_0_project.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths d:/custom_ip/ip_repo/our_dac_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo d:/custom_ip/managed_ip_project/managed_ip_project.tmp/our_dac_v1_0_project/our_dac_v1_0_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/custom_ip/ip_repo/our_dac_1.0/src/sine_lut.mem
  D:/custom_ip/ip_repo/our_dac_1.0/src/triangle_lut.mem
  D:/custom_ip/ip_repo/our_dac_1.0/src/square_lut.mem
}
read_verilog -library "" {
  D:/custom_ip/ip_repo/our_dac_1.0/src/PhaseAccumulator.v
  D:/custom_ip/ip_repo/our_dac_1.0/src/SineROM.v
  D:/custom_ip/ip_repo/our_dac_1.0/src/dac666.v
  {D:/custom_ip/ip_repo/our_dac_1.0/src/module DAC904_WriteModule.v}
  D:/custom_ip/ip_repo/our_dac_1.0/hdl/our_dac_v1_0_S0_AXI.v
  D:/custom_ip/ip_repo/our_dac_1.0/src/reset_sync.v
  D:/custom_ip/ip_repo/our_dac_1.0/hdl/our_dac_v1_0.v
}
read_ip -quiet D:/custom_ip/ip_repo/our_dac_1.0/src/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/custom_ip/ip_repo/our_dac_1.0/src/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/custom_ip/ip_repo/our_dac_1.0/src/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/custom_ip/ip_repo/our_dac_1.0/src/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top our_dac_v1_0 -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef our_dac_v1_0.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file our_dac_v1_0_utilization_synth.rpt -pb our_dac_v1_0_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
