# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0.xci
# IP: The module: 'dac_sys_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_sys_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_sys_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_sys_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0.xci
# IP: The module: 'dac_sys_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_sys_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_sys_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dac_sys_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
