# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/dac_sys_our_dac_0_0.xci
# IP: The module: 'dac_sys_our_dac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/src/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/src/clk_wiz_0/clk_wiz_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: D:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/dac_sys_our_dac_0_0.xci
# IP: The module: 'dac_sys_our_dac_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/src/clk_wiz_0/clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/src/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/custom_ip/our_dac_666/our_dac_666.srcs/sources_1/bd/dac_sys/ip/dac_sys_our_dac_0_0/src/clk_wiz_0/clk_wiz_0_ooc.xdc
