# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/our_dac_666.xdc

# Block Designs: bd/dac_sys/dac_sys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_sys || ORIG_REF_NAME==dac_sys} -quiet] -quiet

# IP: bd/dac_sys/ip/dac_sys_processing_system7_0_0/dac_sys_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_sys_processing_system7_0_0 || ORIG_REF_NAME==dac_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/dac_sys/ip/dac_sys_our_dac_0_0/dac_sys_our_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_sys_our_dac_0_0 || ORIG_REF_NAME==dac_sys_our_dac_0_0} -quiet] -quiet

# IP: bd/dac_sys/ip/dac_sys_ps7_0_axi_periph_0/dac_sys_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_sys_ps7_0_axi_periph_0 || ORIG_REF_NAME==dac_sys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dac_sys/ip/dac_sys_rst_ps7_0_100M_0/dac_sys_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==dac_sys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/dac_sys/ip/dac_sys_auto_pc_0/dac_sys_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dac_sys_auto_pc_0 || ORIG_REF_NAME==dac_sys_auto_pc_0} -quiet] -quiet

# XDC: bd/dac_sys/dac_sys_ooc.xdc
